/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PtRouteImport } from './routes/pt'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as JpRouteImport } from './routes/jp'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as FrRouteImport } from './routes/fr'
import { Route as EsRouteImport } from './routes/es'
import { Route as DeRouteImport } from './routes/de'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ActivationGuideRouteImport } from './routes/activation-guide'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductWindows11ProfessionalKey1PcRouteImport } from './routes/product.windows-11-professional-key-1-pc'
import { Route as ProductVisioProfessional2024Key1PcRouteImport } from './routes/product.visio-professional-2024-key-1-pc'
import { Route as ProductProjectProfessional2024Key1PcRouteImport } from './routes/product.project-professional-2024-key-1-pc'
import { Route as ProductPowerpoint2024ProductKey1PcRouteImport } from './routes/product.powerpoint-2024-product-key-1-pc'
import { Route as ProductOutlook2024ProductKey1PcRouteImport } from './routes/product.outlook-2024-product-key-1-pc'
import { Route as ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRouteImport } from './routes/product.office-365-professional-plus-5-devices-100gb-1-year-key'
import { Route as ProductOffice2024ProfessionalPlusLtscKey1PcRouteImport } from './routes/product.office-2024-professional-plus-ltsc-key-1-pc'
import { Route as ProductOffice2024HomeBusinessForMac1MacKeyRouteImport } from './routes/product.office-2024-home-business-for-mac-1-mac-key'
import { Route as ProductOffice2021ProfessionalPlusRouteImport } from './routes/product.office-2021-professional-plus'
import { Route as ProductOffice2021HomeBusinessForMac1MacKeyRouteImport } from './routes/product.office-2021-home-business-for-mac-1-mac-key'
import { Route as ProductOffice2019ProfessionalPlusRouteImport } from './routes/product.office-2019-professional-plus'
import { Route as ProductOffice2019HomeBusinessForMac1MacKeyRouteImport } from './routes/product.office-2019-home-business-for-mac-1-mac-key'
import { Route as ProductMicrosoft365Family6Users6Tb1YearKeyRouteImport } from './routes/product.microsoft-365-family-6-users-6-tb-1-year-key'
import { Route as ProductExcel2024ProductKey1PcRouteImport } from './routes/product.excel-2024-product-key-1-pc'
import { Route as ProductEsetSmartSecurityPremium1Device1YearKeyRouteImport } from './routes/product.eset-smart-security-premium-1-device-1-year-key'
import { Route as ProductAccess2024ProductKey1PcRouteImport } from './routes/product.access-2024-product-key-1-pc'
import { Route as BlogHowToFindMicrosoftOfficeProductKeyRouteImport } from './routes/blog.how-to-find-microsoft-office-product-key'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const JpRoute = JpRouteImport.update({
  id: '/jp',
  path: '/jp',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationGuideRoute = ActivationGuideRouteImport.update({
  id: '/activation-guide',
  path: '/activation-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductWindows11ProfessionalKey1PcRoute =
  ProductWindows11ProfessionalKey1PcRouteImport.update({
    id: '/product/windows-11-professional-key-1-pc',
    path: '/product/windows-11-professional-key-1-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductVisioProfessional2024Key1PcRoute =
  ProductVisioProfessional2024Key1PcRouteImport.update({
    id: '/product/visio-professional-2024-key-1-pc',
    path: '/product/visio-professional-2024-key-1-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductProjectProfessional2024Key1PcRoute =
  ProductProjectProfessional2024Key1PcRouteImport.update({
    id: '/product/project-professional-2024-key-1-pc',
    path: '/product/project-professional-2024-key-1-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductPowerpoint2024ProductKey1PcRoute =
  ProductPowerpoint2024ProductKey1PcRouteImport.update({
    id: '/product/powerpoint-2024-product-key-1-pc',
    path: '/product/powerpoint-2024-product-key-1-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductOutlook2024ProductKey1PcRoute =
  ProductOutlook2024ProductKey1PcRouteImport.update({
    id: '/product/outlook-2024-product-key-1-pc',
    path: '/product/outlook-2024-product-key-1-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRoute =
  ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRouteImport.update({
    id: '/product/office-365-professional-plus-5-devices-100gb-1-year-key',
    path: '/product/office-365-professional-plus-5-devices-100gb-1-year-key',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductOffice2024ProfessionalPlusLtscKey1PcRoute =
  ProductOffice2024ProfessionalPlusLtscKey1PcRouteImport.update({
    id: '/product/office-2024-professional-plus-ltsc-key-1-pc',
    path: '/product/office-2024-professional-plus-ltsc-key-1-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductOffice2024HomeBusinessForMac1MacKeyRoute =
  ProductOffice2024HomeBusinessForMac1MacKeyRouteImport.update({
    id: '/product/office-2024-home-business-for-mac-1-mac-key',
    path: '/product/office-2024-home-business-for-mac-1-mac-key',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductOffice2021ProfessionalPlusRoute =
  ProductOffice2021ProfessionalPlusRouteImport.update({
    id: '/product/office-2021-professional-plus',
    path: '/product/office-2021-professional-plus',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductOffice2021HomeBusinessForMac1MacKeyRoute =
  ProductOffice2021HomeBusinessForMac1MacKeyRouteImport.update({
    id: '/product/office-2021-home-business-for-mac-1-mac-key',
    path: '/product/office-2021-home-business-for-mac-1-mac-key',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductOffice2019ProfessionalPlusRoute =
  ProductOffice2019ProfessionalPlusRouteImport.update({
    id: '/product/office-2019-professional-plus',
    path: '/product/office-2019-professional-plus',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductOffice2019HomeBusinessForMac1MacKeyRoute =
  ProductOffice2019HomeBusinessForMac1MacKeyRouteImport.update({
    id: '/product/office-2019-home-business-for-mac-1-mac-key',
    path: '/product/office-2019-home-business-for-mac-1-mac-key',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductMicrosoft365Family6Users6Tb1YearKeyRoute =
  ProductMicrosoft365Family6Users6Tb1YearKeyRouteImport.update({
    id: '/product/microsoft-365-family-6-users-6-tb-1-year-key',
    path: '/product/microsoft-365-family-6-users-6-tb-1-year-key',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductExcel2024ProductKey1PcRoute =
  ProductExcel2024ProductKey1PcRouteImport.update({
    id: '/product/excel-2024-product-key-1-pc',
    path: '/product/excel-2024-product-key-1-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductEsetSmartSecurityPremium1Device1YearKeyRoute =
  ProductEsetSmartSecurityPremium1Device1YearKeyRouteImport.update({
    id: '/product/eset-smart-security-premium-1-device-1-year-key',
    path: '/product/eset-smart-security-premium-1-device-1-year-key',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductAccess2024ProductKey1PcRoute =
  ProductAccess2024ProductKey1PcRouteImport.update({
    id: '/product/access-2024-product-key-1-pc',
    path: '/product/access-2024-product-key-1-pc',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToFindMicrosoftOfficeProductKeyRoute =
  BlogHowToFindMicrosoftOfficeProductKeyRouteImport.update({
    id: '/blog/how-to-find-microsoft-office-product-key',
    path: '/blog/how-to-find-microsoft-office-product-key',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activation-guide': typeof ActivationGuideRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/de': typeof DeRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/help-center': typeof HelpCenterRoute
  '/jp': typeof JpRoute
  '/licenses': typeof LicensesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pt': typeof PtRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/how-to-find-microsoft-office-product-key': typeof BlogHowToFindMicrosoftOfficeProductKeyRoute
  '/product/access-2024-product-key-1-pc': typeof ProductAccess2024ProductKey1PcRoute
  '/product/eset-smart-security-premium-1-device-1-year-key': typeof ProductEsetSmartSecurityPremium1Device1YearKeyRoute
  '/product/excel-2024-product-key-1-pc': typeof ProductExcel2024ProductKey1PcRoute
  '/product/microsoft-365-family-6-users-6-tb-1-year-key': typeof ProductMicrosoft365Family6Users6Tb1YearKeyRoute
  '/product/office-2019-home-business-for-mac-1-mac-key': typeof ProductOffice2019HomeBusinessForMac1MacKeyRoute
  '/product/office-2019-professional-plus': typeof ProductOffice2019ProfessionalPlusRoute
  '/product/office-2021-home-business-for-mac-1-mac-key': typeof ProductOffice2021HomeBusinessForMac1MacKeyRoute
  '/product/office-2021-professional-plus': typeof ProductOffice2021ProfessionalPlusRoute
  '/product/office-2024-home-business-for-mac-1-mac-key': typeof ProductOffice2024HomeBusinessForMac1MacKeyRoute
  '/product/office-2024-professional-plus-ltsc-key-1-pc': typeof ProductOffice2024ProfessionalPlusLtscKey1PcRoute
  '/product/office-365-professional-plus-5-devices-100gb-1-year-key': typeof ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRoute
  '/product/outlook-2024-product-key-1-pc': typeof ProductOutlook2024ProductKey1PcRoute
  '/product/powerpoint-2024-product-key-1-pc': typeof ProductPowerpoint2024ProductKey1PcRoute
  '/product/project-professional-2024-key-1-pc': typeof ProductProjectProfessional2024Key1PcRoute
  '/product/visio-professional-2024-key-1-pc': typeof ProductVisioProfessional2024Key1PcRoute
  '/product/windows-11-professional-key-1-pc': typeof ProductWindows11ProfessionalKey1PcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activation-guide': typeof ActivationGuideRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/de': typeof DeRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/help-center': typeof HelpCenterRoute
  '/jp': typeof JpRoute
  '/licenses': typeof LicensesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pt': typeof PtRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/how-to-find-microsoft-office-product-key': typeof BlogHowToFindMicrosoftOfficeProductKeyRoute
  '/product/access-2024-product-key-1-pc': typeof ProductAccess2024ProductKey1PcRoute
  '/product/eset-smart-security-premium-1-device-1-year-key': typeof ProductEsetSmartSecurityPremium1Device1YearKeyRoute
  '/product/excel-2024-product-key-1-pc': typeof ProductExcel2024ProductKey1PcRoute
  '/product/microsoft-365-family-6-users-6-tb-1-year-key': typeof ProductMicrosoft365Family6Users6Tb1YearKeyRoute
  '/product/office-2019-home-business-for-mac-1-mac-key': typeof ProductOffice2019HomeBusinessForMac1MacKeyRoute
  '/product/office-2019-professional-plus': typeof ProductOffice2019ProfessionalPlusRoute
  '/product/office-2021-home-business-for-mac-1-mac-key': typeof ProductOffice2021HomeBusinessForMac1MacKeyRoute
  '/product/office-2021-professional-plus': typeof ProductOffice2021ProfessionalPlusRoute
  '/product/office-2024-home-business-for-mac-1-mac-key': typeof ProductOffice2024HomeBusinessForMac1MacKeyRoute
  '/product/office-2024-professional-plus-ltsc-key-1-pc': typeof ProductOffice2024ProfessionalPlusLtscKey1PcRoute
  '/product/office-365-professional-plus-5-devices-100gb-1-year-key': typeof ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRoute
  '/product/outlook-2024-product-key-1-pc': typeof ProductOutlook2024ProductKey1PcRoute
  '/product/powerpoint-2024-product-key-1-pc': typeof ProductPowerpoint2024ProductKey1PcRoute
  '/product/project-professional-2024-key-1-pc': typeof ProductProjectProfessional2024Key1PcRoute
  '/product/visio-professional-2024-key-1-pc': typeof ProductVisioProfessional2024Key1PcRoute
  '/product/windows-11-professional-key-1-pc': typeof ProductWindows11ProfessionalKey1PcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activation-guide': typeof ActivationGuideRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/de': typeof DeRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/help-center': typeof HelpCenterRoute
  '/jp': typeof JpRoute
  '/licenses': typeof LicensesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/pt': typeof PtRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/how-to-find-microsoft-office-product-key': typeof BlogHowToFindMicrosoftOfficeProductKeyRoute
  '/product/access-2024-product-key-1-pc': typeof ProductAccess2024ProductKey1PcRoute
  '/product/eset-smart-security-premium-1-device-1-year-key': typeof ProductEsetSmartSecurityPremium1Device1YearKeyRoute
  '/product/excel-2024-product-key-1-pc': typeof ProductExcel2024ProductKey1PcRoute
  '/product/microsoft-365-family-6-users-6-tb-1-year-key': typeof ProductMicrosoft365Family6Users6Tb1YearKeyRoute
  '/product/office-2019-home-business-for-mac-1-mac-key': typeof ProductOffice2019HomeBusinessForMac1MacKeyRoute
  '/product/office-2019-professional-plus': typeof ProductOffice2019ProfessionalPlusRoute
  '/product/office-2021-home-business-for-mac-1-mac-key': typeof ProductOffice2021HomeBusinessForMac1MacKeyRoute
  '/product/office-2021-professional-plus': typeof ProductOffice2021ProfessionalPlusRoute
  '/product/office-2024-home-business-for-mac-1-mac-key': typeof ProductOffice2024HomeBusinessForMac1MacKeyRoute
  '/product/office-2024-professional-plus-ltsc-key-1-pc': typeof ProductOffice2024ProfessionalPlusLtscKey1PcRoute
  '/product/office-365-professional-plus-5-devices-100gb-1-year-key': typeof ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRoute
  '/product/outlook-2024-product-key-1-pc': typeof ProductOutlook2024ProductKey1PcRoute
  '/product/powerpoint-2024-product-key-1-pc': typeof ProductPowerpoint2024ProductKey1PcRoute
  '/product/project-professional-2024-key-1-pc': typeof ProductProjectProfessional2024Key1PcRoute
  '/product/visio-professional-2024-key-1-pc': typeof ProductVisioProfessional2024Key1PcRoute
  '/product/windows-11-professional-key-1-pc': typeof ProductWindows11ProfessionalKey1PcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation-guide'
    | '/cookie-policy'
    | '/de'
    | '/es'
    | '/fr'
    | '/help-center'
    | '/jp'
    | '/licenses'
    | '/privacy-policy'
    | '/pt'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/support'
    | '/terms-of-service'
    | '/blog/how-to-find-microsoft-office-product-key'
    | '/product/access-2024-product-key-1-pc'
    | '/product/eset-smart-security-premium-1-device-1-year-key'
    | '/product/excel-2024-product-key-1-pc'
    | '/product/microsoft-365-family-6-users-6-tb-1-year-key'
    | '/product/office-2019-home-business-for-mac-1-mac-key'
    | '/product/office-2019-professional-plus'
    | '/product/office-2021-home-business-for-mac-1-mac-key'
    | '/product/office-2021-professional-plus'
    | '/product/office-2024-home-business-for-mac-1-mac-key'
    | '/product/office-2024-professional-plus-ltsc-key-1-pc'
    | '/product/office-365-professional-plus-5-devices-100gb-1-year-key'
    | '/product/outlook-2024-product-key-1-pc'
    | '/product/powerpoint-2024-product-key-1-pc'
    | '/product/project-professional-2024-key-1-pc'
    | '/product/visio-professional-2024-key-1-pc'
    | '/product/windows-11-professional-key-1-pc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation-guide'
    | '/cookie-policy'
    | '/de'
    | '/es'
    | '/fr'
    | '/help-center'
    | '/jp'
    | '/licenses'
    | '/privacy-policy'
    | '/pt'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/support'
    | '/terms-of-service'
    | '/blog/how-to-find-microsoft-office-product-key'
    | '/product/access-2024-product-key-1-pc'
    | '/product/eset-smart-security-premium-1-device-1-year-key'
    | '/product/excel-2024-product-key-1-pc'
    | '/product/microsoft-365-family-6-users-6-tb-1-year-key'
    | '/product/office-2019-home-business-for-mac-1-mac-key'
    | '/product/office-2019-professional-plus'
    | '/product/office-2021-home-business-for-mac-1-mac-key'
    | '/product/office-2021-professional-plus'
    | '/product/office-2024-home-business-for-mac-1-mac-key'
    | '/product/office-2024-professional-plus-ltsc-key-1-pc'
    | '/product/office-365-professional-plus-5-devices-100gb-1-year-key'
    | '/product/outlook-2024-product-key-1-pc'
    | '/product/powerpoint-2024-product-key-1-pc'
    | '/product/project-professional-2024-key-1-pc'
    | '/product/visio-professional-2024-key-1-pc'
    | '/product/windows-11-professional-key-1-pc'
  id:
    | '__root__'
    | '/'
    | '/activation-guide'
    | '/cookie-policy'
    | '/de'
    | '/es'
    | '/fr'
    | '/help-center'
    | '/jp'
    | '/licenses'
    | '/privacy-policy'
    | '/pt'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/support'
    | '/terms-of-service'
    | '/blog/how-to-find-microsoft-office-product-key'
    | '/product/access-2024-product-key-1-pc'
    | '/product/eset-smart-security-premium-1-device-1-year-key'
    | '/product/excel-2024-product-key-1-pc'
    | '/product/microsoft-365-family-6-users-6-tb-1-year-key'
    | '/product/office-2019-home-business-for-mac-1-mac-key'
    | '/product/office-2019-professional-plus'
    | '/product/office-2021-home-business-for-mac-1-mac-key'
    | '/product/office-2021-professional-plus'
    | '/product/office-2024-home-business-for-mac-1-mac-key'
    | '/product/office-2024-professional-plus-ltsc-key-1-pc'
    | '/product/office-365-professional-plus-5-devices-100gb-1-year-key'
    | '/product/outlook-2024-product-key-1-pc'
    | '/product/powerpoint-2024-product-key-1-pc'
    | '/product/project-professional-2024-key-1-pc'
    | '/product/visio-professional-2024-key-1-pc'
    | '/product/windows-11-professional-key-1-pc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationGuideRoute: typeof ActivationGuideRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DeRoute: typeof DeRoute
  EsRoute: typeof EsRoute
  FrRoute: typeof FrRoute
  HelpCenterRoute: typeof HelpCenterRoute
  JpRoute: typeof JpRoute
  LicensesRoute: typeof LicensesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PtRoute: typeof PtRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  BlogHowToFindMicrosoftOfficeProductKeyRoute: typeof BlogHowToFindMicrosoftOfficeProductKeyRoute
  ProductAccess2024ProductKey1PcRoute: typeof ProductAccess2024ProductKey1PcRoute
  ProductEsetSmartSecurityPremium1Device1YearKeyRoute: typeof ProductEsetSmartSecurityPremium1Device1YearKeyRoute
  ProductExcel2024ProductKey1PcRoute: typeof ProductExcel2024ProductKey1PcRoute
  ProductMicrosoft365Family6Users6Tb1YearKeyRoute: typeof ProductMicrosoft365Family6Users6Tb1YearKeyRoute
  ProductOffice2019HomeBusinessForMac1MacKeyRoute: typeof ProductOffice2019HomeBusinessForMac1MacKeyRoute
  ProductOffice2019ProfessionalPlusRoute: typeof ProductOffice2019ProfessionalPlusRoute
  ProductOffice2021HomeBusinessForMac1MacKeyRoute: typeof ProductOffice2021HomeBusinessForMac1MacKeyRoute
  ProductOffice2021ProfessionalPlusRoute: typeof ProductOffice2021ProfessionalPlusRoute
  ProductOffice2024HomeBusinessForMac1MacKeyRoute: typeof ProductOffice2024HomeBusinessForMac1MacKeyRoute
  ProductOffice2024ProfessionalPlusLtscKey1PcRoute: typeof ProductOffice2024ProfessionalPlusLtscKey1PcRoute
  ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRoute: typeof ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRoute
  ProductOutlook2024ProductKey1PcRoute: typeof ProductOutlook2024ProductKey1PcRoute
  ProductPowerpoint2024ProductKey1PcRoute: typeof ProductPowerpoint2024ProductKey1PcRoute
  ProductProjectProfessional2024Key1PcRoute: typeof ProductProjectProfessional2024Key1PcRoute
  ProductVisioProfessional2024Key1PcRoute: typeof ProductVisioProfessional2024Key1PcRoute
  ProductWindows11ProfessionalKey1PcRoute: typeof ProductWindows11ProfessionalKey1PcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp': {
      id: '/jp'
      path: '/jp'
      fullPath: '/jp'
      preLoaderRoute: typeof JpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation-guide': {
      id: '/activation-guide'
      path: '/activation-guide'
      fullPath: '/activation-guide'
      preLoaderRoute: typeof ActivationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/windows-11-professional-key-1-pc': {
      id: '/product/windows-11-professional-key-1-pc'
      path: '/product/windows-11-professional-key-1-pc'
      fullPath: '/product/windows-11-professional-key-1-pc'
      preLoaderRoute: typeof ProductWindows11ProfessionalKey1PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/visio-professional-2024-key-1-pc': {
      id: '/product/visio-professional-2024-key-1-pc'
      path: '/product/visio-professional-2024-key-1-pc'
      fullPath: '/product/visio-professional-2024-key-1-pc'
      preLoaderRoute: typeof ProductVisioProfessional2024Key1PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/project-professional-2024-key-1-pc': {
      id: '/product/project-professional-2024-key-1-pc'
      path: '/product/project-professional-2024-key-1-pc'
      fullPath: '/product/project-professional-2024-key-1-pc'
      preLoaderRoute: typeof ProductProjectProfessional2024Key1PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/powerpoint-2024-product-key-1-pc': {
      id: '/product/powerpoint-2024-product-key-1-pc'
      path: '/product/powerpoint-2024-product-key-1-pc'
      fullPath: '/product/powerpoint-2024-product-key-1-pc'
      preLoaderRoute: typeof ProductPowerpoint2024ProductKey1PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/outlook-2024-product-key-1-pc': {
      id: '/product/outlook-2024-product-key-1-pc'
      path: '/product/outlook-2024-product-key-1-pc'
      fullPath: '/product/outlook-2024-product-key-1-pc'
      preLoaderRoute: typeof ProductOutlook2024ProductKey1PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/office-365-professional-plus-5-devices-100gb-1-year-key': {
      id: '/product/office-365-professional-plus-5-devices-100gb-1-year-key'
      path: '/product/office-365-professional-plus-5-devices-100gb-1-year-key'
      fullPath: '/product/office-365-professional-plus-5-devices-100gb-1-year-key'
      preLoaderRoute: typeof ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/office-2024-professional-plus-ltsc-key-1-pc': {
      id: '/product/office-2024-professional-plus-ltsc-key-1-pc'
      path: '/product/office-2024-professional-plus-ltsc-key-1-pc'
      fullPath: '/product/office-2024-professional-plus-ltsc-key-1-pc'
      preLoaderRoute: typeof ProductOffice2024ProfessionalPlusLtscKey1PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/office-2024-home-business-for-mac-1-mac-key': {
      id: '/product/office-2024-home-business-for-mac-1-mac-key'
      path: '/product/office-2024-home-business-for-mac-1-mac-key'
      fullPath: '/product/office-2024-home-business-for-mac-1-mac-key'
      preLoaderRoute: typeof ProductOffice2024HomeBusinessForMac1MacKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/office-2021-professional-plus': {
      id: '/product/office-2021-professional-plus'
      path: '/product/office-2021-professional-plus'
      fullPath: '/product/office-2021-professional-plus'
      preLoaderRoute: typeof ProductOffice2021ProfessionalPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/office-2021-home-business-for-mac-1-mac-key': {
      id: '/product/office-2021-home-business-for-mac-1-mac-key'
      path: '/product/office-2021-home-business-for-mac-1-mac-key'
      fullPath: '/product/office-2021-home-business-for-mac-1-mac-key'
      preLoaderRoute: typeof ProductOffice2021HomeBusinessForMac1MacKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/office-2019-professional-plus': {
      id: '/product/office-2019-professional-plus'
      path: '/product/office-2019-professional-plus'
      fullPath: '/product/office-2019-professional-plus'
      preLoaderRoute: typeof ProductOffice2019ProfessionalPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/office-2019-home-business-for-mac-1-mac-key': {
      id: '/product/office-2019-home-business-for-mac-1-mac-key'
      path: '/product/office-2019-home-business-for-mac-1-mac-key'
      fullPath: '/product/office-2019-home-business-for-mac-1-mac-key'
      preLoaderRoute: typeof ProductOffice2019HomeBusinessForMac1MacKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/microsoft-365-family-6-users-6-tb-1-year-key': {
      id: '/product/microsoft-365-family-6-users-6-tb-1-year-key'
      path: '/product/microsoft-365-family-6-users-6-tb-1-year-key'
      fullPath: '/product/microsoft-365-family-6-users-6-tb-1-year-key'
      preLoaderRoute: typeof ProductMicrosoft365Family6Users6Tb1YearKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/excel-2024-product-key-1-pc': {
      id: '/product/excel-2024-product-key-1-pc'
      path: '/product/excel-2024-product-key-1-pc'
      fullPath: '/product/excel-2024-product-key-1-pc'
      preLoaderRoute: typeof ProductExcel2024ProductKey1PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/eset-smart-security-premium-1-device-1-year-key': {
      id: '/product/eset-smart-security-premium-1-device-1-year-key'
      path: '/product/eset-smart-security-premium-1-device-1-year-key'
      fullPath: '/product/eset-smart-security-premium-1-device-1-year-key'
      preLoaderRoute: typeof ProductEsetSmartSecurityPremium1Device1YearKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/access-2024-product-key-1-pc': {
      id: '/product/access-2024-product-key-1-pc'
      path: '/product/access-2024-product-key-1-pc'
      fullPath: '/product/access-2024-product-key-1-pc'
      preLoaderRoute: typeof ProductAccess2024ProductKey1PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-find-microsoft-office-product-key': {
      id: '/blog/how-to-find-microsoft-office-product-key'
      path: '/blog/how-to-find-microsoft-office-product-key'
      fullPath: '/blog/how-to-find-microsoft-office-product-key'
      preLoaderRoute: typeof BlogHowToFindMicrosoftOfficeProductKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationGuideRoute: ActivationGuideRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DeRoute: DeRoute,
  EsRoute: EsRoute,
  FrRoute: FrRoute,
  HelpCenterRoute: HelpCenterRoute,
  JpRoute: JpRoute,
  LicensesRoute: LicensesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PtRoute: PtRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  BlogHowToFindMicrosoftOfficeProductKeyRoute:
    BlogHowToFindMicrosoftOfficeProductKeyRoute,
  ProductAccess2024ProductKey1PcRoute: ProductAccess2024ProductKey1PcRoute,
  ProductEsetSmartSecurityPremium1Device1YearKeyRoute:
    ProductEsetSmartSecurityPremium1Device1YearKeyRoute,
  ProductExcel2024ProductKey1PcRoute: ProductExcel2024ProductKey1PcRoute,
  ProductMicrosoft365Family6Users6Tb1YearKeyRoute:
    ProductMicrosoft365Family6Users6Tb1YearKeyRoute,
  ProductOffice2019HomeBusinessForMac1MacKeyRoute:
    ProductOffice2019HomeBusinessForMac1MacKeyRoute,
  ProductOffice2019ProfessionalPlusRoute:
    ProductOffice2019ProfessionalPlusRoute,
  ProductOffice2021HomeBusinessForMac1MacKeyRoute:
    ProductOffice2021HomeBusinessForMac1MacKeyRoute,
  ProductOffice2021ProfessionalPlusRoute:
    ProductOffice2021ProfessionalPlusRoute,
  ProductOffice2024HomeBusinessForMac1MacKeyRoute:
    ProductOffice2024HomeBusinessForMac1MacKeyRoute,
  ProductOffice2024ProfessionalPlusLtscKey1PcRoute:
    ProductOffice2024ProfessionalPlusLtscKey1PcRoute,
  ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRoute:
    ProductOffice365ProfessionalPlus5Devices100gb1YearKeyRoute,
  ProductOutlook2024ProductKey1PcRoute: ProductOutlook2024ProductKey1PcRoute,
  ProductPowerpoint2024ProductKey1PcRoute:
    ProductPowerpoint2024ProductKey1PcRoute,
  ProductProjectProfessional2024Key1PcRoute:
    ProductProjectProfessional2024Key1PcRoute,
  ProductVisioProfessional2024Key1PcRoute:
    ProductVisioProfessional2024Key1PcRoute,
  ProductWindows11ProfessionalKey1PcRoute:
    ProductWindows11ProfessionalKey1PcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
